FROM 47f8bde36e22
MAINTAINER dgvncsz0f

ADD dev-bootstrap.sh /var/tmp/bootstrap.sh
ADD leela-recv-build.sh /bin/leela-recv-build
ADD https://github.com/zeromq/jzmq/archive/v2.2.2.zip /var/tmp/jzmq-v2.2.2.zip
RUN /var/tmp/bootstrap.sh
