# -*- mode: makefile-gmake; -*-

bin_dash       = sh
bin_find       = find
bin_xargs      = xargs
bin_ghc        = ghc
bin_virtualenv = virtualenv
bin_cabal      = cabal
bin_lsof       = lsof
bin_socat      = socat
bin_curl       = curl
bin_date       = date
bin_sed        = sed
bin_install    = install

bin_twistd     = twistd
bin_nosetests  = nosetests
bin_shelltest  = shelltest
bin_python     = python

pyenv          = PYTHONPATH=$(srcroot)/src/server
hsenv          = PATH=$$PATH:$(HOME)/.cabal/bin

nosetestsargs  =
# ghcargs        = -optc-O3 -fexcess-precision -optc-march=corei7
ghcargs        =
shelltestargs  =
shelltestpath  = $(srcroot)/try/smoke

-include $(userfile)

.saverc:
	$(call check_bin,virtualenv)
	$(call check_bin,cabal)
	$(call check_bin,ghc)
	$(call check_bin,lsof)
	$(call check_bin,find)
	$(call check_bin,socat)
	$(call check_bin,curl)
	$(call check_bin,date)
	$(call check_bin,sed)
	$(call check_bin,xargs)
	echo "bin_virtualenv = $(bin_virtualenv)"                         >$(userfile)
	echo "bin_dash       = $(bin_dash)"                               >>$(userfile)
	echo "bin_ghc        = $(bin_ghc)"                                >>$(userfile)
	echo "bin_cabal      = $(bin_cabal)"                              >>$(userfile)
	echo "bin_lsof       = $(bin_lsof)"                               >>$(userfile)
	echo "bin_find       = $(bin_find)"                               >>$(userfile)
	echo "bin_socat      = $(bin_socat)"                              >>$(userfile)
	echo "bin_curl       = $(bin_curl)"                               >>$(userfile)
	echo "bin_date       = $(bin_date)"                               >>$(userfile)
	echo "bin_sed        = $(bin_sed)"                                >>$(userfile)
	echo "bin_xargs      = $(bin_xargs)"                              >>$(userfile)
	echo "bin_install    = $(bin_install)"                            >>$(userfile)
	echo "bin_nosetests  = $(HOME)/pyenv/leela-server/bin/nosetests"  >>$(userfile)
	echo "bin_twistd     = $(HOME)/pyenv/leela-server/bin/twistd"     >>$(userfile)
	echo "bin_python     = $(HOME)/pyenv/leela-server/bin/python"     >>$(userfile)
	echo "bin_shelltest  = $(HOME)/.cabal/bin/shelltest"              >>$(userfile)

.check_bin = @(command -v $(bin_$(1)) >/dev/null) || {                          \
                        echo "bin_$(1)[=$(bin_$(1))] not found!!!";             \
                        echo;                                                   \
                        echo "Use bin_$(1) variable to fix this, as follows: "; \
                        echo "  $$ $(MAKE) ... bin_$(1)=/path/to/file";         \
                        echo;                                                   \
                        echo "Additionally, you also change the file:";         \
                        echo "  $(userfile)";                                   \
                        echo;                                                   \
                        echo "Although it is likely better to use:";            \
                        echo "  $$ $(MAKE) bootstrap bin_$(1)=/path/to/file";   \
                        echo;                                                   \
                        echo "so that it gets remembered next time";            \
                        exit 1; }
