#!/bin/sh

daemon_pidfile=/var/run/leela/dmproc.pid

[ -r /etc/default/leela-dmproc    ] && . /etc/default/leela-dmproc
[ -r /usr/libexec/leela-functions ] && . /usr/libexec/leela-functions

# 1. check proc has creates pidfile and is up & running
if ! leela_check_pid $daemon_pidfile >/dev/null
then
  nagios_critical "Critical: missing pid file: $pidfile"
fi

# 2. dmproc uses daemon, so the real deal is the child pid
daemon_pid=$(cat $daemon_pidfile)
if ! ps --ppid $daemon_pid >/dev/null
then
  nagios_critical "Critical: dmproc process not found"
fi

# 2. check it is listening on correct unix socket
pid=$(ps -o pid= --ppid $daemon_pid)
xsock=${DMPROC_SOCKET:-/var/run/leela/dmproc}
if ! leela_check_xsock $pid $xsock >/dev/null
then
  nagios_critical "Critical: dmproc not connected unix socket: $xsock"
fi

# 3. check it is reading the fifo
fifo=${DMPROC_DATABUS:-/var/run/leela/dmproc-databus}
if ! leela_check_file $pid $fifo >/dev/null
then
  nagios_critical "Critical: dmproc not reading from fifo: $fifo"
fi

nagios_ok "Ok: check_leela_dmproc"
