#!/bin/sh

pidfile=/var/run/leela/udp.pid

[ -r /usr/libexec/leela-functions ] && . /usr/libexec/leela-functions

# 1. check proc has creates pidfile and is up & running
if ! leela_check_pid $pidfile >/dev/null
then
  nagios_critical "Critical: missing pid file: $pidfile"
fi

# 2. check it is listening on correct udp port
pid=$(cat $pidfile)
port=$(leela_read_udp_port)
if ! leela_check_inet $pid udp:$port >/dev/null
then
  nagios_critical "Critical: proc not connected to udp port: $port"
fi

# 3. check it is writing to all fifo files
leela_read_udp_broadcast | \
    while read fifo
    do
      if ! leela_check_file $pid $fifo >/dev/null
      then
        nagios_critical "Critical: not connected to fifo: $fifo"
      fi
    done

nagios_ok "Ok: check_leela_udp"
