#!/bin/sh

pidfile=/var/run/leela/http.pid

[ -r /usr/libexec/leela-functions ] && . /usr/libexec/leela-functions

# 1. check proc has creates pidfile and is up & running
if ! leela_check_pid $pidfile >/dev/null
then
  nagios_critical "Critical: missing pid file: $pidfile"
fi

# 2. check it is listening on correct tcp port
pid=$(cat $pidfile)
port=$(leela_read_http_port)
if ! leela_check_inet $pid tcp:$port >/dev/null
then
  nagios_critical "Critical: proc not connected to tcp port: $port"
fi

# 3. check it is writing to all fifo files
# leela_read_http_broadcast | \
#     while read fifo
#     do
#       if ! leela_check_file $pid $fifo >/dev/null
#       then
#         nagios_critical "Critical: not connected to fifo: $fifo"
#       fi
#     done

nagios_ok "Ok: check_leela_http"
