;; Copyright 2014 (c) Diego Souza <dsouza@c0d3.xxx>
;;
;; Licensed under the Apache License, Version 2.0 (the "License");
;; you may not use this file except in compliance with the License.
;; You may obtain a copy of the License at
;;
;;     http://www.apache.org/licenses/LICENSE-2.0
;;
;; Unless required by applicable law or agreed to in writing, software
;; distributed under the License is distributed on an "AS IS" BASIS,
;; WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
;; See the License for the specific language governing permissions and
;; limitations under the License.
;;
;; [DO NOT EDIT, AUTOMATICALLY GENERATED BY (./src/scripts/version.sh /home/dsouza/dev/locaweb/leela/src/blackbox/src/leela/version.clj)]

(ns leela.version)

(def major 6)

(def minor 2)

(def patch 0)

(def version "6.2.0")

