
# poly1305aes Makefile.lib version 20050218
# D. J. Bernstein
# Public domain.

poly1305aes: poly1305aes.a poly1305aes.h poly1305.h aes.h

poly1305aes.h: poly1305aes.impl \
poly1305aes.h.do
	sh -e poly1305aes.h.do > poly1305aes.h.new
	mv poly1305aes.h.new poly1305aes.h

poly1305.h: poly1305aes.impl \
poly1305.h.do
	sh -e poly1305.h.do > poly1305.h.new
	mv poly1305.h.new poly1305.h

aes.h: poly1305aes.impl \
aes.h.do
	sh -e aes.h.do > aes.h.new
	mv aes.h.new aes.h

poly1305aes.a: poly1305aes.impl \
poly1305aes.a.do \
aes_aix.h \
aes_aix.s \
aes_aix_constants.s \
aes_athlon.h \
aes_athlon.s \
aes_athlon_constants.s \
aes_big.c \
aes_big.h \
aes_big_constants.c \
aes_macos.h \
aes_macos.s \
aes_macos_constants.s \
aes_ppro.h \
aes_ppro.s \
aes_ppro_constants.s \
aes_sparc.h \
aes_sparc.s \
aes_sparc_constants.c \
poly1305_53.c \
poly1305_53.h \
poly1305_53_constants.c \
poly1305_aix.h \
poly1305_aix.s \
poly1305_aix_constants.c \
poly1305_athlon.h \
poly1305_athlon.s \
poly1305_athlon_constants.s \
poly1305_macos.h \
poly1305_macos.s \
poly1305_macos_constants.s \
poly1305_ppro.h \
poly1305_ppro.s \
poly1305_ppro_constants.s \
poly1305_sparc.h \
poly1305_sparc.s \
poly1305_sparc_constants.c \
poly1305aes_53.h \
poly1305aes_53_authenticate.c \
poly1305aes_53_clamp.c \
poly1305aes_53_isequal.c \
poly1305aes_53_verify.c \
poly1305aes_aix.h \
poly1305aes_aix_authenticate.c \
poly1305aes_aix_clamp.c \
poly1305aes_aix_isequal.s \
poly1305aes_aix_verify.c \
poly1305aes_athlon.h \
poly1305aes_athlon_authenticate.c \
poly1305aes_athlon_clamp.c \
poly1305aes_athlon_isequal.s \
poly1305aes_athlon_verify.c \
poly1305aes_macos.h \
poly1305aes_macos_authenticate.c \
poly1305aes_macos_clamp.c \
poly1305aes_macos_isequal.s \
poly1305aes_macos_verify.c \
poly1305aes_ppro.h \
poly1305aes_ppro_authenticate.c \
poly1305aes_ppro_clamp.c \
poly1305aes_ppro_isequal.s \
poly1305aes_ppro_verify.c \
poly1305aes_sparc.h \
poly1305aes_sparc_authenticate.c \
poly1305aes_sparc_clamp.s \
poly1305aes_sparc_fsr.s \
poly1305aes_sparc_isequal.s \
poly1305aes_sparc_verify.c
	sh -e poly1305aes.a.do $(CC) > poly1305aes.a.new
	mv poly1305aes.a.new poly1305aes.a

poly1305aes.impl: \
poly1305aes.impl.do \
x86cpuid.c \
poly1305aes.impl.check.c \
aes_aix.h \
aes_aix.s \
aes_aix_constants.s \
aes_athlon.h \
aes_athlon.s \
aes_athlon_constants.s \
aes_big.c \
aes_big.h \
aes_big_constants.c \
aes_macos.h \
aes_macos.s \
aes_macos_constants.s \
aes_ppro.h \
aes_ppro.s \
aes_ppro_constants.s \
aes_sparc.h \
aes_sparc.s \
aes_sparc_constants.c \
poly1305_53.c \
poly1305_53.h \
poly1305_53_constants.c \
poly1305_aix.h \
poly1305_aix.s \
poly1305_aix_constants.c \
poly1305_athlon.h \
poly1305_athlon.s \
poly1305_athlon_constants.s \
poly1305_macos.h \
poly1305_macos.s \
poly1305_macos_constants.s \
poly1305_ppro.h \
poly1305_ppro.s \
poly1305_ppro_constants.s \
poly1305_sparc.h \
poly1305_sparc.s \
poly1305_sparc_constants.c \
poly1305aes_53.h \
poly1305aes_53_authenticate.c \
poly1305aes_53_clamp.c \
poly1305aes_53_isequal.c \
poly1305aes_53_verify.c \
poly1305aes_aix.h \
poly1305aes_aix_authenticate.c \
poly1305aes_aix_clamp.c \
poly1305aes_aix_isequal.s \
poly1305aes_aix_verify.c \
poly1305aes_athlon.h \
poly1305aes_athlon_authenticate.c \
poly1305aes_athlon_clamp.c \
poly1305aes_athlon_isequal.s \
poly1305aes_athlon_verify.c \
poly1305aes_macos.h \
poly1305aes_macos_authenticate.c \
poly1305aes_macos_clamp.c \
poly1305aes_macos_isequal.s \
poly1305aes_macos_verify.c \
poly1305aes_ppro.h \
poly1305aes_ppro_authenticate.c \
poly1305aes_ppro_clamp.c \
poly1305aes_ppro_isequal.s \
poly1305aes_ppro_verify.c \
poly1305aes_sparc.h \
poly1305aes_sparc_authenticate.c \
poly1305aes_sparc_clamp.s \
poly1305aes_sparc_fsr.s \
poly1305aes_sparc_isequal.s \
poly1305aes_sparc_verify.c
	sh -e poly1305aes.impl.do $(CC) > poly1305aes.impl.new
	mv poly1305aes.impl.new poly1305aes.impl
