#!/bin/sh

### BEGIN INIT INFO
# Provides:          leela-dmproc
# Required-Start:    $network $local_fs
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Collect and chart anything
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin
DAEMON=/usr/bin/dmproc
PIDFILE=/var/run/leela/dmproc.pid
LOGFILE=/var/log/leela/dmproc.log

[ -x "$DAEMON" ]                    || exit 0
[ -r /etc/default/leela-dmproc ]    && . /etc/default/leela-dmproc
[ -r /lib/lsb/init-functions ]      && . /lib/lsb/init-functions
[ -r /usr/libexec/leela-functions ] && . /usr/libexec/leela-functions

start_service() {
  pipefile=${DMPROC_DATABUS:-/var/run/leela/dmproc-databus}
  sockfile=${DMPROC_SOCKET:-/var/run/leela/dmproc}
  log_daemon_msg "starting $DAEMON"
  start-stop-daemon -N-5 -Sq -p $PIDFILE -x /usr/bin/daemon -- -u leela:leela $DAEMON_OPTS -F $PIDFILE -o $LOGFILE -- $DAEMON +RTS -N${DMPROC_THREADS} -RTS -vvv $pipefile $sockfile
  log_end_msg $?
}

stop_service() {
  pipefile=${DMPROC_DATABUS:-/var/run/leela/dmproc-databus}
  sockfile=${DMPROC_SOCKET:-/var/run/leela/dmproc}
  log_daemon_msg "stopping $DAEMON"
  start-stop-daemon -Kq -R 10 -p $PIDFILE
  log_end_msg $?
  rm -f $PIDFILE
  rm -f $pipefile
  rm -f $sockfile
}

case "$1" in
  start)
    start_service
    ;;

  stop)
    stop_service
    ;;

  restart)
    stop_service
    start_service
    ;;

  *)
    echo "Usage: $0 {start|stop|restart}" >&2
    exit 3
    ;;
esac

exit 0
