#!/bin/sh
### BEGIN INIT INFO
# Provides:          leela-storage
# Required-Start:    $network $local_fs
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Distributed, real time event processor and monitoring engine
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin
FSROOT=${FSROOT:-/}
DAEMON=/usr/bin/twistd
SERVICE=storage
RUNDIR=/var/run/leela
PIDFILE=$RUNDIR/$SERVICE.pid
LOGFILE=/var/log/leela/$SERVICE.log
SOCKFILE=$RUNDIR/storage
USER=leela
GROUP=leela

[ -x "$DAEMON" ]                            || exit 0
[ -r /lib/lsb/init-functions ]              && . /lib/lsb/init-functions
[ -r ${FSROOT}etc/default/leela-$SERVICE ]  && . ${FSROOT}etc/default/leela-$SERVICE
[ -r ${FSROOT}usr/libexec/leela-functions ] && . ${FSROOT}usr/libexec/leela-functions

start_service () {
  mkdir -p $RUNDIR
  chown $USER:$GROUP $RUNDIR
  proc_id=$1
  pidfile=$PIDFILE-$proc_id
  logfile=$LOGFILE-$proc_id
  pipefile=$SOCKFILE-$proc_id
  log_daemon_msg "starting $DAEMON [$SERVICE/$proc_id]"
  start-stop-daemon -Sq -c $USER:$GROUP -p $pidfile -x $DAEMON -- --logfile=$logfile --pidfile=$pidfile leela --service=$SERVICE --setenv=pipe:$pipefile $DAEMON_OPTS
  log_end_msg $?
}

stop_service () {
  proc_id=$1
  pidfile=$PIDFILE-$proc_id
  pipefile=$SOCKFILE-$proc_id
  log_daemon_msg "stopping $DAEMON [$SERVICE/$proc_id]"
  start-stop-daemon -Kq -R 10 -p $pidfile
  log_end_msg $?
  rm -f $pidfile
  rm -f $pipefile
}

restart_service () {
  stop_service $1
  start_service $1
}

case "$1" in
  start)
    repeat ${NPROCS:-1} start_service
    ;;

  stop)
    repeat ${NPROCS:-1} stop_service
    ;;

  restart)
    repeat ${NPROCS:-1} restart_service
    ;;

  *)
    echo "Usage: $0 {start|stop|restart}" >&2
    exit 3
    ;;
esac

exit 0
