#!/bin/sh
### BEGIN INIT INFO
# Provides:          leela-http
# Required-Start:    $network $local_fs $leela-storage
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Distributed, real time event processor and monitoring engine
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin
FSROOT=${FSROOT:-/}
DAEMON=/usr/bin/twistd
SERVICE=http
RUNDIR=/var/run/leela
PIDFILE=$RUNDIR/$SERVICE.pid
LOGFILE=/var/log/leela/$SERVICE.log
USER=leela
GROUP=leela

[ -x "$DAEMON" ]                            || exit 0
[ -r /lib/lsb/init-functions ]              && . /lib/lsb/init-functions
[ -r ${FSROOT}etc/default/leela-$SERVICE ]  && . ${FSROOT}etc/default/leela-$SERVICE
[ -r ${FSROOT}usr/libexec/leela-functions ] && . ${FSROOT}usr/libexec/leela-functions

start_service () {
  mkdir -p $RUNDIR
  chown $USER:$GROUP $RUNDIR
  log_daemon_msg "starting $DAEMON [$SERVICE]"
  start-stop-daemon -N-5 -c $USER:$GROUP -Sq -p $PIDFILE -x $DAEMON -- --logfile=$LOGFILE --pidfile=$PIDFILE leela --service=$SERVICE $DAEMON_OPTS
  log_end_msg $?
}

stop_service () {
  log_daemon_msg "stopping $DAEMON [$SERVICE]"
  start-stop-daemon -Kq -R 10 -p $PIDFILE
  log_end_msg $?
  rm -f $PIDFILE
}

restart_service () {
  stop_service
  start_service
}

case "$1" in
  start)
    start_service
    ;;

  stop)
    stop_service
    ;;

  restart)
    restart_service
    ;;

  *)
    echo "Usage: $0 {start|stop|restart}" >&2
    exit 3
    ;;
esac

exit 0
