#!/bin/sh
### BEGIN INIT INFO
# Provides:          leela
# Required-Start:    $network $remote_fs
# Required-Stop:     $network $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Distributed, real time event processor and monitoring engine
### END INIT INFO

leela_do () {
  for srv in timeline dmproc multicast http storage xmpp collectd udp
  do
    "${CHDIR}/etc/init.d/leela-$srv" "$@"
  done
}

case "$1" in
  start)
    leela_do start
    ;;

  stop)
    leela_do stop
    ;;

  restart|force-reload)
    leela_do stop
    leela_do start
    ;;
  
  *)
    echo "Usage: $0 {start|stop|restart}" >&2
    exit 3
    ;;
esac

exit 0
