#!/bin/sh
### BEGIN INIT INFO
# Provides:          leela-storage
# Required-Start:    $network $local_fs
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Distributed, real time event processor and monitoring engine
### END INIT INFO

PATH="${CHDIR}/bin:${CHDIR}/usr/bin:$PATH"
DAEMON=twistd
RUNDIR="${CHDIR}/var/run/leela"
SERVICE=storage
PIDFILE="$RUNDIR/$SERVICE.pid"
LOGFILE="${CHDIR}/var/log/leela/$SERVICE.log"
USER=leela
GROUP=leela

DATABUS=${DATABUS:-/tmp/storage-databus}

[ -r "${CHDIR}/etc/default/leela-$SERVICE"  ] && . "${CHDIR}/etc/default/leela-$SERVICE"
[ -r "${CHDIR}/usr/libexec/leela-functions" ] && . "${CHDIR}/usr/libexec/leela-functions"
[ "$ENABLED" = "true"                       ] || leela_exit_with "error: leela-$SERVICE is disabled" 1
leela_test_x "$DAEMON"                        || leela_exit_with "error: $DAEMON not found" 1

start_service () {
  local instance logfile pidfile databus

  instance=${NPROC:-1}
  logfile=$LOGFILE
  pidfile=$PIDFILE
  databus=$DATABUS
  while [ $instance -gt 0 ]
  do
    instance=$(( $instance - 1 ))
    LOGFILE="$logfile.$instance"
    PIDFILE="$pidfile.$instance"
    DATABUS="$databus.$instance"
    INSTANCE=$instance
    leela_twistd_start ${SERVICE_OPTS:---config="${CHDIR}/etc/leela.conf"} "--setenv=databus:$DATABUS"
  done
}

stop_service () {
  local instance logfile pidfile databus

  instance=${NPROC:-1}
  logfile=$LOGFILE
  pidfile=$PIDFILE
  databus=$DATABUS
  while [ $instance -gt 0 ]
  do
    instance=$(( $instance - 1 ))
    LOGFILE="$logfile.$instance"
    PIDFILE="$pidfile.$instance"
    DATABUS="$databus.$instance"
    INSTANCE=$instance
    leela_generic_stop
    rm -f "$DATABUS"
  done
}

case "$1" in
  start)
    start_service
    ;;

  stop)
    stop_service
    ;;

  *)
    echo "Usage: $0 {start|stop}" >&2
    exit 3
    ;;
esac

exit 0
