#!/bin/sh

### BEGIN INIT INFO
# Provides:          leela-timeline
# Required-Start:    $network $local_fs
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Distributed, real time event processor and monitoring engine
### END INIT INFO

PATH="${CHDIR}/bin:${CHDIR}/usr/bin:$PATH"
DAEMON=daemon
SERVICE="${CHDIR}/usr/bin/timeline"
RUNDIR="${CHDIR}/var/run/leela"
PIDFILE="$RUNDIR/timeline.pid"
LOGFILE="${CHDIR}/var/log/leela/timeline.log"
USER=leela
GROUP=leela

TIMELINE_DATABUS=${TIMELINE_DATABUS:-/tmp/timeline-databus}
TIMELINE_MULTICAST=${TIMELINE_MULTICAST:-/tmp/timeline-multicast}
TIMELINE_QUEUES=${TIMELINE_QUEUES:-1}

[ -r "${CHDIR}/etc/default/leela-timeline"  ] && . ${CHDIR}/etc/default/leela-timeline
[ -r "${CHDIR}/usr/libexec/leela-functions" ] && . ${CHDIR}/usr/libexec/leela-functions
[ "$ENABLED" = "true"                       ] || leela_exit_with "error: leela-timeline is disabled" 1
leela_test_x "$DAEMON"                        || leela_exit_with "error: $DAEMON not found" 1
leela_test_x "$SERVICE"                       || leela_exit_with "error: $SERVICE not found" 1

start_service() {
  leela_daemon_start +RTS -N${TIMELINE_THREADS} -RTS -v $TIMELINE_OPTS -q$TIMELINE_QUEUES "$TIMELINE_DATABUS" "$TIMELINE_MULTICAST"
}

stop_service() {
  leela_generic_stop
  rm -f "$TIMELINE_DATABUS" "$TIMELINE_MULTICAST"
}

case "$1" in
  start)
    start_service
    ;;

  stop)
    stop_service
    ;;

  *)
    echo "Usage: $0 {start|stop}" >&2
    exit 3
    ;;
esac

exit 0
