#!/bin/sh
### BEGIN INIT INFO
# Provides:          leela-xmpp
# Required-Start:    $network $local_fs $leela-timeline
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Distributed, real time event processor and monitoring engine
### END INIT INFO

DAEMON=twistd
RUNDIR="$CHDIR/var/run/leela"
SERVICE=xmpp
PIDFILE="$RUNDIR/$SERVICE.pid"
LOGFILE="$CHDIR/var/log/leela/$SERVICE.log"
USER=leela
GROUP=leela

[ -r "${CHDIR}/etc/default/leela-$SERVICE"  ] && . "${CHDIR}/etc/default/leela-$SERVICE"
[ -r "${CHDIR}/usr/libexec/leela-functions" ] && . "${CHDIR}/usr/libexec/leela-functions"
leela_test_x "$DAEMON"                        || exit 1

start_service () {
  leela_twistd_start ${SERVICE_OPTS:---config="$CHDIR/etc/leela.conf"}
}

stop_service () {
  leela_generic_stop
}

case "$1" in
  start)
    start_service
    ;;

  stop)
    stop_service
    ;;

  *)
    echo "Usage: $0 {start|stop}" >&2
    exit 3
    ;;
esac

exit 0
