#!/bin/bash

if [ "$1" = "purge" ] ; then
    userdel leela >/dev/null 2>&1 || true
    groupdel leela >/dev/null 2>&1 || true
fi

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d leela-web remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d leela-server remove >/dev/null
fi
# End automatically added section
