#!/bin/sh

exec 2>>/tmp/try-leela.stderr

. ./try/golden/lib/trylib.sh
. ./try/golden/lib/tryudp.sh
. ./try/golden/lib/tryxmpp.sh
. ./try/golden/lib/trydmproc.sh
. ./try/golden/lib/tryhttp.sh
. ./try/golden/lib/trystorage.sh

test -f $pidfile && { kill $(cat $pidfile); sleep 1; }
rm -f $sockfile $dbusfile

"$@"
