#!/bin/sh

# template:chdir

now=$(date +%s)
rnd=$(( RANDOM ))
key_udp=leela.selftest.${now}_${rnd}.udp
key_http=leela.selftest.${now}_${rnd}.http
len_udp=$(echo -n $key_udp | wc -c)
len_http=$(echo -n $key_http | wc -c)

leela_interact () {
  $CHDIR/usr/libexec/leela-interact
}

test_udp_ping () {
  echo pong >$1/exp

  cat <<EOF | tee $1/inp | leela_interact >$1/out
udp-send message=ping\n
EOF
}

test_udp () {
  cat <<EOF >$1/exp
{"results": {"$key_udp": {"series": [[0, ${rnd}.0]]}}, "status": 200}
event $len_udp|$key_udp ${rnd}.0 0.0;
EOF

  cat <<EOF | tee $1/inp | leela_interact >$1/out
dmproc-connect "proc=proc match 15|^leela.selftest id;"
udp-send "message=gauge $len_udp|$key_udp $rnd {now};"
sleep seconds=5
http-request method=GET url=/v1/past24/$key_udp
dmproc-disconnect
EOF
}

test_http () {
  cat <<EOF >$1/exp
{"results": [{"name": "$key_http", "timestamp": 0.0, "type": "gauge", "value": ${rnd}.0}], "status": 201}
{"results": {"$key_http": {"series": [[0, ${rnd}.0]]}}, "status": 200}
event $len_http|$key_http ${rnd}.0 0.0;
EOF

  cat <<EOF | tee $1/inp | leela_interact >$1/out
dmproc-connect "proc=proc match 15|^leela.selftest id;"
http-request method=POST url=/v1/$key_http 'data={"type": "gauge", "value": ${rnd}, "timestamp": {now}}'
http-request method=GET url=/v1/past24/$key_http
dmproc-disconnect
EOF
}

for t in test_udp_ping   \
         test_udp
do
  TEMPFILE=$(mktemp -d) && {
    $t $TEMPFILE
    if cmp -b $TEMPFILE/exp $TEMPFILE/out
    then
      echo "$t: ok"
      rm -rf $TEMPFILE
    else
      # rm -rf $TEMPFILE
      exit 1
    fi
  }
done
