#!/bin/sh

leela_test_x () {
  command -v "$1" >/dev/null
}

leela_exit_with () {
  echo "$1"
  exit $2
}

leela_log_exitcode () {
  local code service daemon instance
  code=$1
  daemon=$(basename "$DAEMON")
  service=$(basename "$SERVICE")
  instance=""
  if [ -n "$INSTANCE" ]
  then instance="[$INSTANCE]"; fi
  if [ "$code" -eq 0 ]
  then
    echo "$daemon.$service$instance OK"
  else
    echo "$daemon.$service$instance FAIL [exit=$code]"
  fi
}

leela_daemon_start () {
  if [ $(id -u) -eq 0 ]
  then
    DAEMON_OPTS="-u $USER:$GROUP $DAEMON_OPTS"
  else
    DAEMON_OPTS=""
  fi
  "$DAEMON" $DAEMON_OPTS -F "$PIDFILE" -o "$LOGFILE" "$SERVICE" -- "$@"
  leela_log_exitcode $?
}

retry_while () {
  local retry
  retry=10

  while "$@"
  do
    sleep 1
    retry=$(( $retry - 1 ))
    if [ $retry -lt 0 ];
    then break; fi
  done
}

leela_wait_pid () {
  test -n "$1" && ps -p "$1" >>/dev/null
}

leela_generic_stop () {
  local pid

  pid=$(test -r "$PIDFILE" && cat "$PIDFILE")
  test -n "$pid" && kill $pid
  leela_log_exitcode $?

  test -n "$pid" && retry_while leela_wait_pid $pid
  rm -f "$PIDFILE"
}

leela_twistd_start () {
  if [ $(id -u) -eq 0 ]
  then
    DAEMON_OPTS="-u $USER -g $GROUP"
  else
    DAEMON_OPTS=""
  fi
  $DAEMON $DAEMON_OPTS --logfile="$LOGFILE" --pidfile="$PIDFILE" leela --service="$SERVICE" "$@"
  leela_log_exitcode $?
}
