#!/usr/bin/python
#
# Copyright 2012 Juliano Martinez
# All Rights Reserved.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#
# @author: Juliano Martinez

import os
import bz2
import sys
import pwd
import getopt
import gevent
import syslog
from leela import config
from supay import Daemon
from gevent import socket
from leela import lasergun

myname = sys.argv[0].split('/')[-1]
syslog.openlog(myname, syslog.LOG_PID, syslog.LOG_DAEMON)

def main(username):
    os.setuid(pwd.getpwnam(username)[2])
    syslog.syslog("Starting...")

    s = socket.socket(family=socket.AF_INET, type=socket.SOCK_DGRAM, proto=socket.IPPROTO_UDP)
    s.bind((config.get('server','address'), config.getint('server', 'port')))

    while True:
        data, peer = s.recvfrom(16384)
        data = bz2.decompress(data)
        syslog.syslog("New data: %s" % data)
        gevent.spawn(lasergun.parse_and_save_datagram, data)

if __name__ == '__main__':
    try:
        opts, args = getopt.getopt(sys.argv[1:], "a:u:", ["action=","username="])
    except getopt.GetoptError, err:
        print str(err)
        sys.exit(1)

    action = 'start'
    username = 'leela'
    for o, v in opts:
        if o in ('-a', '--action'):
            action = v
        if o in ('-u', '--username'):
            username = v

    daemon = Daemon(name='leela-server', catch_all_log="/var/log/leela-server.log")
    if action == 'start':
        daemon.start()
        main(username)
    elif action == 'status':
        daemon.status()
    elif action == 'stop':
        daemon.stop()
    elif action == 'foreground':
        main(username)
