#!/usr/bin/python
#
# Copyright 2012 Juliano Martinez
# All Rights Reserved.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#
# @author: Juliano Martinez

import os
import sys
import json
import syslog
import pycassa
import datetime
import ConfigParser
from pycassa.system_manager import SystemManager

def show_all():
    systemManager = pycassa.system_manager.SystemManager(timeout=600)
    columnFamilies = systemManager.get_keyspace_column_families('leela')
    pool = pycassa.ConnectionPool('leela', server_list=['127.0.0.1'])
    for columnFamilyName in columnFamilies:
        client = pycassa.ColumnFamily(pool, columnFamilyName)
        for data in client.get_range(buffer=12000):
            print data

def show(cf):
    pool = pycassa.ConnectionPool('leela', server_list=['127.0.0.1'])
    client = pycassa.ColumnFamily(pool, cf)
    for _, data in client.get_range(column_count=12000):
        #print data
        for name, value in data.iteritems():
            print name, value
            #name, ts = name.split('||')
            #print name, ts



if __name__ == '__main__':
    show(sys.argv[1])
