#!/usr/bin/python
#
# Copyright 2012 Juliano Martinez
# All Rights Reserved.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#
# @author: Juliano Martinez

from gevent import monkey
monkey.patch_all()

import re
import os
import pwd
import sys
import json
import syslog
import getopt
import pycassa
import ConfigParser
from supay import Daemon
from leela import lasergun
from leela import config
from datetime import datetime
from optparse import OptionParser
from bottle import route, run, request, response, ServerAdapter
from bottle import abort, default_app, post, delete, debug, get, static_file

syslog.openlog(sys.argv[0].split('/')[-1], syslog.LOG_PID, syslog.LOG_DAEMON)
cassandra = config.get('cassandra','server')

def reply_json(f):
    def call(*args, **kwargs):
        data = f(*args, **kwargs)
        cc   = request.GET.get("callback") or ""
        if (re.match("^[a-zA-Z0-9_\.]+$", cc)):
            response.content_type = "application/javascript; charset=utf-8"
            return("%s(%s);" % (cc, json.dumps(data)))
        else:
            response.content_type = "application/json; charset=utf-8"
            return(json.dumps(data))
    return(call)

@get('/%s/<hostname>/<service>/<date>' % config.get('web','chart_endpoint'))
def generate_chart(hostname, service, date):
    try:
        syslog.syslog("Received connection looking for leela chart")
        if not hostname:
            syslog.syslog("No hostname given")
            abort(404, 'No hostname given')

        ColumnFamily = 'hour'
        if len(date) == 8:
            ColumnFamily = 'day'
        elif len(date) == 6:
            ColumnFamily = 'month'
        elif len(date) == 4:
            ColumnFamily = 'year'

        pool = pycassa.ConnectionPool('leela', server_list=[cassandra])
        client = pycassa.ColumnFamily(pool, ColumnFamily)
        series = {}
        skey = "%s:%s:%s" % (hostname, service.capitalize(), date)
        for key, value in client.get(skey).iteritems():
            name, ts = key.split('||')
            if not series.has_key(name):
                series[name] = []
            """ it is really fucking stupid but have to be used
                http://highslide.com/forum/viewtopic.php?f=9&t=9551&p=44143 """
            series[name].append([float(ts) * 1000, value])

        return """%s""" % lasergun.render_template(
            "/usr/share/leela/templates/line-irregular.tmpl",
            service,
            hostname,
            series
        )

    except Exception, e:
        syslog.syslog("Error: %s" % e.__str__())
        print("Error: %s" % e.__str__())
        abort(500, json.dumps(e.__str__()))
    abort(404, '%s not found' % hostname)

@get('/%s/<hostname>/<service>/<date>' % config.get('web','json_endpoint'))
@reply_json
def generate_json(hostname, service, date):
    try:
        syslog.syslog("Received connection looking for leela json")
        if not hostname:
            syslog.syslog("No hostname given")
            abort(404, 'No hostname given')

        ColumnFamily = 'hour'
        if len(date) == 8:
            ColumnFamily = 'day'
        elif len(date) == 6:
            ColumnFamily = 'month'
        elif len(date) == 4:
            ColumnFamily = 'year'

        pool = pycassa.ConnectionPool('leela', server_list=[cassandra])
        client = pycassa.ColumnFamily(pool, ColumnFamily)
        series = {}
        skey = "%s:%s:%s" % (hostname, service.capitalize(), date)
        for key, value in client.get(skey).iteritems():
            name, ts = key.split('||')
            if not series.has_key(name):
                series[name] = []
            series[name].append([float(ts), value])

        return series

    except Exception, e:
        syslog.syslog("Error: %s" % e.__str__())
        print("Error: %s" % e.__str__())
        abort(500, json.dumps(e.__str__()))
    abort(404, '%s not found' % hostname)

@get('/static/<path:path>')
def static(path):
    return static_file(path, root='/usr/share/leela/static/')

class GEventServerAdapter(ServerAdapter):
    def run(self, handler):
        from gevent.wsgi import WSGIServer
        WSGIServer((self.host, self.port), handler).serve_forever()

def main(username, port):
    os.setuid(pwd.getpwnam(username)[2])
    syslog.syslog("Starting...")
    run(host = config.get('web','address'),
        port = port or config.getint('web','port'),
        server = GEventServerAdapter)
    debug(True)

if __name__ == '__main__':
    try:
        opts, args = getopt.getopt(sys.argv[1:], "a:u:p:", ["action=","username=","port="])
    except getopt.GetoptError, err:
        print str(err)
        sys.exit(1)

    port = None
    action = 'start'
    username = 'leela'
    for o, v in opts:
        if o in ('-a', '--action'):
            action = v
        if o in ('-u', '--username'):
            username = v
        if o in ('-p', '--port'):
            port = v

    daemon = Daemon(name='leela-web', catch_all_log="/var/log/leela-web.log")
    if action == 'start':
        daemon.start()
        main(username, port)
    elif action == 'status':
        daemon.status()
    elif action == 'stop':
        daemon.stop()
    elif action == 'foreground':
        main(username, port)

